data<-read.table("household_power_consumption.txt",sep=";",na.strings='?',header=TRUE,quote='')
data$date=as.Date(data$Date,"%d/%m/%Y")
data$DateTime=paste(data$Date,data$Time)
data$DateTime=strptime(data$DateTime,"%d/%m/%Y %H:%M:%S")
newdata<-subset(data,data$date=="2007-02-02" | data$date=="2007-02-01")
png(height=480,width=480,file="second.png")
with(newdata,plot(x=DateTime,y=Global_active_power,type="n"))
with(newdata,lines(x=DateTime,y=Global_active_power),ylab="Global Avtice Power(kilowatts)")
dev.off()